---
title: "Project 2 Solutions"
output:
  pdf_document: default
---

```{r, include=F}
# Run this code chunk first to activate the course Python environment.
# Do not remove this. It will not show up in your compiled PDF.
datamine_py()
library(reticulate)

# Install packages if not already installed.
list.of.packages <- c("knitr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

# Remove ## from output.
library(knitr)
opts_chunk$set(comment = NA)

# Wrap output that is too long using r code chunk option linewidth=80
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})
```

## Kevin Choe

## Collaborators: (Collaborators listed here. Include names, which part of the project you gave or sought help with, and how you helped or were helped.)
## TA help: Neha Priyadarshini
## Online resources used: (List of links/resources (if any) here. Include web addresses, which part of the project the resource helped with, and how you were helped.)

### Question 1

```{python, linewidth=80}
import pandas as pd
myDF = pd.read_csv("/class/datamine/data/craigslist/vehicles.csv")
myDF.head()

from pathlib import Path
p = Path("/class/datamine/data/craigslist/vehicles.csv")
p.stat().st_size
print(f'my file size is: {p.stat().st_size/1000000}')

```

### Question 2

```{python, linewidth=80}
myDF.shape
print(f'The number of rows are: {myDF.shape[0]}')
print(f'The number of columns are: {myDF.shape[1]}')
myDF.columns
```

### Question 3

```{python, linewidth=80}
columns = list(myDF.columns)
len(columns)
columns.append("extra")
print(f'Second column name is :{columns[1]}')
print(f'Patterned column names are: {columns[::2]}')
print(f'Last four column names are: {columns[-4:]}')
columns.remove("extra")
```

### Question 4

```{python, linewidth=80}
from matplotlib import pyplot as plt
my_values = list(tuple(myDF.loc[:, 'odometer'].dropna().to_list()))
my_values.sort()
plt.plot(my_values[0:-50], color="blue")
plt.title("Cars vs odometer readings")
plt.xlabel("Amount of cars")
plt.ylabel("Odometer readings")
plt.show()
plt.close()
```

### Question 5

```{python, linewidth=80}
myDF.sort_values(['year', 'price'], inplace = True)
plt.plot(myDF['year'], myDF['price'], color="#FB8072", linestyle="dashed")
plt.title("Price and Year")
plt.xlabel("Price")
plt.ylabel("Year")
plt.show()
plt.close()
```

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.