---
title: "Project 10 Solutions"
output:
  pdf_document: default
---

```{r, include=F}
# Run this code chunk first to activate the course Python environment.
# Do not remove this. It will not show up in your compiled PDF.
datamine_py()
library(reticulate)

# Install packages if not already installed.
list.of.packages <- c("knitr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

# Remove ## from output.
library(knitr)
opts_chunk$set(comment = NA)

# Wrap output that is too long using r code chunk option linewidth=80
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})
```

## Kevin Choe

## Collaborators: (Collaborators listed here. Include names, which part of the project you gave or sought help with, and how you helped or were helped.)
## TA help: Summeth Guda
## Online resources used: (List of links/resources (if any) here. Include web addresses, which part of the project the resource helped with, and how you were helped.)

### Question 1

```{python, linewidth=80}
import pandas as pd
```

```{python, linewidth=80}
import numpy as np
import pandas as pd
beers = pd.read_parquet("/class/datamine/data/beer/beers.parquet")
breweries = pd.read_parquet("/class/datamine/data/beer/breweries.parquet")
reviews = pd.read_parquet("/class/datamine/data/beer/reviews.parquet")
def prepare_data(myDF, min_num_reviews: int):
  myDF = myDF.loc[myDF.loc[:, "score"].notna(), :]
  myDF = myDF.loc[myDF.loc[:, "username"].notna(), :]
  myDF = myDF.loc[myDF.loc[:, "beer_id"].notna(), :]
  myDF.reset_index(drop=True)
  goodbeers = myDF.loc[:, "beer_id"].value_counts() >= min_num_reviews
  goodbeers = goodbeers.loc[goodbeers].index.values.tolist()
  goodusers = myDF.loc[:, "username"].value_counts() >= min_num_reviews
  goodusers = goodusers.loc[goodusers].index.values.tolist()
  myreturnDF = myDF.loc[myDF.loc[:, "username"].isin(goodusers)&myDF.loc[:, "beer_id"].isin(goodbeers), :]
  return myreturnDF
train = prepare_data(reviews, 1000)

def normalize(data):
    data['mean_score'] = data['score'].mean()
    data['std_score'] = data['score'].std()
    data['normalized'] = (data['score'] - data['mean_score'])/data['std_score']
    return data

train= train.groupby(["username"]).apply(normalize)
score_matrix = train.pivot(index='username',columns='beer_id',values='normalized')
myresults=score_matrix.mean(axis=0)
score_matrix=score_matrix.fillna(value=myresults)

from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity_matrix=cosine_similarity(score_matrix)
np.fill_diagonal(cosine_similarity_matrix,0)
cosine_similarity_matrix= pd.DataFrame(cosine_similarity_matrix)
cosine_similarity_matrix.index = score_matrix.index
cosine_similarity_matrix.columns = score_matrix.index
cosine_similarity_matrix[0:4]
cosine_similarity_matrix[1820:]
```

### Question 2

```{python, linewidth=80}
def get_knn (cosine_similarity_matrix,user,k):
  return cosine_similarity_matrix[user].sort_values(ascending=False)[0:k].index.tolist()

k_similar=get_knn(cosine_similarity_matrix,"2GOOFY",4)
print(k_similar) # ['Phil-Fresh', 'mishi_d', 'SlightlyGrey', 'MI_beerdrinker']
```

### Question 3

```{python, linewidth=80}
User="mishi_d"
similar=get_knn(cosine_similarity_matrix,User,1)[0]
similar
aux=pd.DataFrame()
for i in range(0,reviews.shape[0]):
  if(reviews['username'][i]==User or reviews['username'][i]==similar):
    aux=aux.append(reviews.iloc[i])

aux_matrix=aux.pivot(index='beer_id',columns='username',values='score')
aux_matrix=aux_matrix.dropna(axis=0)
aux_matrix.head
#I think that the users rated the beers similarly because of the positive trend in data moving upwards.  
```

### Question 4

```{python, linewidth=80}
def recommend_beers(train: pd.DataFrame, username: str, cosine_similarity_matrix: pd.DataFrame, k: int) -> list:
  k_similar=get_knn(cosine_similarity_matrix, username, k)
  aux = pd.DataFrame(data = train[train["username"].isin(k_similar) == True])
  myBeers = train[train["username"].isin([username]) == True]
  myBeers = myBeers["beer_id"].to_list()
  aux = aux[aux["beer_id"].isin(myBeers) == False]
  aux = aux.loc[:, ("beer_id", "normalized")].groupby(["beer_id"]).mean()
  aux = aux.sort_values(by = "normalized", ascending = False)
  aux = aux.iloc[0:5]
  return aux.index.tolist()
recommend_beers(train, "22Blue", cosine_similarity_matrix, 30) # [40057, 69522, 22172, 59672, 86487]
```

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.
