---
title: "Project 3 Solutions"
output:
  pdf_document: default
---

```{r, include=F}
# Run this code chunk first to activate the course Python environment.
# Do not remove this. It will not show up in your compiled PDF.
datamine_py()
library(reticulate)

# Install packages if not already installed.
list.of.packages <- c("knitr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

# Remove ## from output.
library(knitr)
opts_chunk$set(comment = NA)

# Wrap output that is too long using r code chunk option linewidth=80
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})
```

## Kevin Choe

## Collaborators: (Collaborators listed here. Include names, which part of the project you gave or sought help with, and how you helped or were helped.)
## TA help: Summeth Guda
## Online resources used: (List of links/resources (if any) here. Include web addresses, which part of the project the resource helped with, and how you were helped.)

### Question 1

```{python, linewidth=80}
import pandas as pd
myDF = pd.read_csv("/class/datamine/data/craigslist/vehicles.csv")
myDF.head()
```

### Question 2

```{python, linewidth=80}
myyears = myDF['year'].dropna().to_list()

# get a list containing each unique year
unique_years = list(set(myyears))

# for each year (key), initialize the value (value) to 0
my_dict = {}
for year in unique_years:
    my_dict[year] = 0
for year in myyears:
    my_dict[year] = my_dict[year] + 1
print(my_dict)
```

### Question 3

```{python, linewidth=80}
import matplotlib.pyplot as plt

my_dict.keys()
my_dict.values()
plt.bar(my_dict.keys(), my_dict.values())
plt.show()
plt.close()
# An example of a key would be 1912 has a value of 5.
print(my_dict[1912])
```

### Question 4

```{python, linewidth=80}
listA = [1, 2, 3, 4, 5, 6, 12, 12]
listB = [2, 1, 7, 7, 7, 2, 8, 9, 10, 11, 12, 13]

# 1. values in list A but not list B
# values in list A but not list B
print(set(listA) - set(listB))

# 2. values in listB but not list A
print(set(listB) - set(listA))

# 3. values in both lists
# values in both lists
print(set.intersection(set(listA),set(listB)))
```

### Question 5

```{python, linewidth=80}
states_list = list(myDF.loc[:, ["state", "lat", "long"]].dropna().to_records(index=False))

geoDict = {}
for my_triple in states_list:
  geoDict[my_triple[0]] = []

for i in states_list:
  geoDict[i[0]].append( (i[1], i[2]) )
```

### Question 6

```{python, linewidth=80}
import matplotlib.pyplot as plt

my_dict.keys()
my_dict.values()
plt.scatter(my_dict.keys(), my_dict.values(), color='red')
plt.xlabel("Year")
plt.ylabel("Value");
plt.show()
plt.close()
```

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.